version: "3"
services:

  mysql:
    image: "mysql:5.7"
    container_name: "fwcloud-mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "fwcdbusr"
      MYSQL_PASSWORD: "fwcdbusr"
      MYSQL_DATABASE: "fwcloud"
    volumes:
      - "${HOME}/fwcloud/mysql:/var/lib/mysql"

  fwcloud-api:
    image: "soltecsis/fwcloud-api:1.4.0"
    depends_on:
      - mysql
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -- ./run.sh"]
    environment:
      TYPEORM_HOST: mysql
      TYPEORM_PORT: 3306
      TYPEORM_DATABASE: "fwcloud"
      TYPEORM_USERNAME: "fwcdbusr"
      TYPEORM_PASSWORD: fwcdbusr
      CORS_WHITELIST: 'http://localhost:3030'
    ports:
      - 127.0.0.1:3131:3131
    volumes:
      - "${HOME}/fwcloud/DATA:/fwcloud-api/DATA"
      - "${HOME}/fwcloud/sessions:/fwcloud-api/sessions"
      - "${HOME}/fwcloud/BACKUP:/fwcloud-api/BACKUP"
      - "${HOME}/fwcloud/logs:/fwcloud-api/logs"
      - "${HOME}/fwcloud/config:/config"

  fwcloud-ui:
    image: "soltecsis/fwcloud-ui:1.3.1"
    environment:
      FWC_API_URL: "http://fwcloud-api:3131"
      HTTPS_ENABLED: "false"
    ports:
      - 3030:3030

    
