version: "3"
services:

  mariadb:
    image: "mariadb:latest"
    container_name: "fwcloud-mariadb"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "fwcdbusr"
      MARIADB_PASSWORD: "fwcdbusr"
      MARIADB_DATABASE: "fwcloud"
    volumes:
      - "./fwcloud-docker/db:/var/lib/mysql"

  fwcloud-api:
    image: "soltecsis/fwcloud-api:latest"
    container_name: "fwcloud-api"
    depends_on:
      - mariadb
    command: ["sh", "-c", "./wait-for-it.sh mariadb:3306 -- ./run.sh"]
    environment:
      TYPEORM_HOST: mariadb
      TYPEORM_PORT: 3306
      TYPEORM_DATABASE: "fwcloud"
      TYPEORM_USERNAME: "fwcdbusr"
      TYPEORM_PASSWORD: fwcdbusr
    volumes:
      - "./fwcloud-docker/api/DATA:/opt/fwcloud/api/DATA"
      - "./fwcloud-docker/api/sessions:/opt/fwcloud/api/sessions"
      - "./fwcloud-docker/api/BACKUP:/opt/fwcloud/api/BACKUP"
      - "./fwcloud-docker/api/logs:/opt/fwcloud/api/logs"
      - "./fwcloud-docker/api/config:/config"

  fwcloud-ui:
    image: "soltecsis/fwcloud-ui:latest"
    container_name: "fwcloud-ui"
    environment:
      FWC_API_URL: "https://fwcloud-api:3131"
    volumes:
      - "./fwcloud-docker/websrv/logs:/opt/fwcloud/websrv/logs"
      - "./fwcloud-docker/websrv/config:/config"
    ports:
      - 3030:3030
