version: "3"
services:

  mariadb:
    image: "mariadb:latest"
    container_name: "fwcloud-mariadb"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "fwcdbusr"
      MARIADB_PASSWORD: "fwcdbusr"
      MARIADB_DATABASE: "fwcloud"
    volumes:
      - "${HOME}/fwcloud/mariadb:/var/lib/mariadb"

  fwcloud-api:
    image: "soltecsis/fwcloud-api:latest"
    depends_on:
      - mariadb
    command: ["sh", "-c", "./wait-for-it.sh mariadb:3306 -- ./run.sh"]
    environment:
      TYPEORM_HOST: mariadb
      TYPEORM_PORT: 3306
      TYPEORM_DATABASE: "fwcloud"
      TYPEORM_USERNAME: "fwcdbusr"
      TYPEORM_PASSWORD: fwcdbusr
      CORS_WHITELIST: 'http://localhost:3030'
    ports:
      - 127.0.0.1:3131:3131
    volumes:
      - "${HOME}/fwcloud/DATA:/fwcloud-api/DATA"
      - "${HOME}/fwcloud/sessions:/fwcloud-api/sessions"
      - "${HOME}/fwcloud/BACKUP:/fwcloud-api/BACKUP"
      - "${HOME}/fwcloud/logs:/fwcloud-api/logs"
      - "${HOME}/fwcloud/config:/config"

  fwcloud-ui:
    image: "soltecsis/fwcloud-ui:latest"
    environment:
      FWC_API_URL: "http://fwcloud-api:3131"
      HTTPS_ENABLED: "false"
    ports:
      - 3030:3030

    
